### ISSUE TITLE
[PyPI] Replace Deprecated PyPI XMLRPC Methods in DataFed Python API

### ISSUE THREAD

**Issue by suruihuang** [ORNL/DataFed#1086]
#  Description
DataFed currently uses deprecated XMLRPC methods from PyPI, which causes runtime errors on deployed sites.

# Issue Details
When attempting to connect to PyPI, the following runtime error occurs:
``
Unable to connect to PyPI: <Fault -32500: 'RuntimeError: PyPI no longer supports the XMLRPC package_releases method. Use JSON or Simple API instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.'> 
``
Consider replacing deprecated XMLRPC methods with the current JSON or Simple API alternatives recommended by PyPI in ``python/datafed_pkg/datafed/MessageLib.py``

**Comment by JoshuaSBrown** [comment]
Running returns this.

```
PYTHONPATH=. ./scripts/datafed
Unable to connect to pypi: <Fault -32500: 'RuntimeError: PyPI no longer supports the XMLRPC package_releases method. Use JSON or Simple API instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.'>
Manual authentication required.
User ID: ^C
```

@suruihuang does this still let you continue using the client other than throwing the error? It should catch it and continue.

**Comment by JoshuaSBrown** [comment]
Looks like sort order is reversed by default.

```
(datafed) brownjs@LAP142548:~/software/open/datafed/DataFed_Copy/python/datafed_pkg$ PYTHONPATH=. ./scripts/datafed --verbosity 2
['0.10.0', '0.11.0', '0.13.0', '0.7.19', '0.7.20', '1.1.0-0', '1.1.0-1', '1.1.0-4', '1.2.0-4', '1.4.0-0', '2.0.0', '2.0.1', '2.0.2', '2.0.3', '3.0.0']
Final release
0.10.0
```

**Comment by JoshuaSBrown** [comment]
#1115
