### ISSUE TITLE
Error in DataFed Python Package from outdated package_releases method.

### ISSUE THREAD

**Issue by nedvedba** [ORNL/DataFed#1115]
The DataFed python package appears to be broken for recent versions of Python on PyPI as PyPI no longer supports the XMLRPC package_releases method, and recommends using JSON or Simple API instead. We need to swap to one of these more modern methods and redeploy the package to PyPI.

Relevant Documentation
[https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods](https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods)

**Comment by JoshuaSBrown** [comment]
# Acceptance 

Test that pip installed package works with jupyternotebook.
