### ISSUE TITLE
[Build, CI, Docker] Docker container GCS Collection Mount Bug

### ISSUE THREAD

**Issue by AronPerez** [ORNL/DataFed#1149]
## Description
When running docker compose up , the shared volume with the host and container is having issues with a directory being created in it via the entrypoint_authz.sh script. 

This directory is needed for:
* GCS to transfer files to and 
* DataFed to manage said files

### Theory
If directories don't exist on the host, will docker dameon in root mode create them with root perms?

_it does_
```shell
drwxr-xr-x  2 root  root  4096 Nov 27 11:20 compose_collection
```

## Steps to Reproduce
1. Build images
2. docker compose up
3. See `<DATAFED_GCS_COLLECTION_ROOT_PATH>/<DATAFED_REPO_ID_AND_DIR>` be unable to take files
4. Directory isn't created on shared volume in container due to permissions issues.

## Error
```shell
datafed-gcs-1   | mkdir: cannot create directory '/mnt/datafed/compose-home/user': Permission denied
datafed-gcs-1   | mkdir: cannot create directory '/mnt/datafed/compose-home/project': Permission denied
```

**Comment by JoshuaSBrown** [comment]
@AronPerez has nothing been done to fix this problem yet?
