### ISSUE TITLE
Setup a Globus endpoint for testing purposes only 

### ISSUE THREAD

**Issue by marshallmcdonnell** [ORNL/DataFed#276]
Need to setup a Globus endpoint strictly for automated testing (ie in a CI fashion).

Current plan of work:
- [x] Get access to DEV server (sdms.ornl.gov) 
- [x] Setup a VM server in CADES for this testing endpoint (may try to figure out how to do this with Terraform -> OpenStack, but need to research; put IaC files in repo if so)
- [x] Get current `globus-connect-server.conf` on the DEV server (sdms.ornl.gov) and move over to this new test VM
- [x] Request firewall exceptions
- [ ] Ensure we can add that endpoint to an account we use for this testing; may need to talk to our Organizational Globus sys admin / engineer (Richard Prout?) to get it up an running
- [ ] Do basic testing of transfer (push and pull a file)

Will need to then look into installing the data repository code on this server repeatedly and any restart of the service to allow changes in data repo code to take place (ie libauthz code sits at the GridFTP level I believe). Will try to get this setup as a container and mount any necessary volume for the endpoint (but may not have to, we'll see)

Related issue: #270

**Comment by JoshuaSBrown** [comment]
This has been done and is implemented as part of the datafedci repository on GitLab.
