### ISSUE TITLE
Scripted stand-up / tear-down of ArangoDB

### ISSUE THREAD

**Issue by marshallmcdonnell** [ORNL/DataFed#277]
Need to be able to stand up and tear down the ArangoDB via automated scripting.

Steps for work include:
- [ ] Just try to do a "hello world" install of ArangoDB on test system
- [ ] Look over scripts in repository mentioned below under `core/database` and `db_create.js` to initialize DataFed DB
- [ ] Test installation in the `test` environment

Comments from @dvstans on the re-install for DEV server:
> So I'm just now reinstalling ArangoDB from scratch (sort of). 3.6.1 is the latest version. I just checked-in three new scripts into the devel branch under core/database. The "db_create.js" scipt can be used to initialize the sdms DB once arango is installed and configured. Take a look at the /etc/arangodb3/arangod.conf and arangosh.conf files - there are only a few setting changed here from default. There's a process to setting the DB root password - it's documented on the Arango site.
> ...you still have to install the DataFed microservice once the DB is up. I do this manually currently through the DB web UI, but I'd guess there's a way to do it via scripting.

**Comment by JoshuaSBrown** [comment]
@dvstans I'm going to close this issue, this will be covered while integrating the CI with SLATE. Will link this issue there as a reference.

**Comment by dvstans** [comment]
Sounds good.
