### ISSUE TITLE
Investigate / setup a CI pipeline

### ISSUE THREAD

**Issue by marshallmcdonnell** [ORNL/DataFed#278]
Overall, want to figure out if we can accomplish the following ideal setup:

1. Commit code to a sub-component (ie `core`, `client`, or `repository` and eventually also the `web` sub-components)

2. In the CI pipeline, on test runners, initially kick off (ie on feature branches):
	i) Build of the sub-component
	ii) Unit test the sub-component ("no other component needed" testing)
	iii) Any possible integration testing with `devel` or `master` artifacts ready to stand up.

3. Then, in next stage of CI pipeline (this might be a Pull Request only build, not for feature branches):
 	i) Build the entire system (such as how it is now with CMake from top-level but maybe break up into multiple builds of each component)
	ii) Perform integration tests with our Globus testing endpoint (Issue #276) and a fresh ArangoDB for the `core` (Issue #277)

4. Then, could either of the following (or both):
	- stress test for load
	- Version the sub-component and have a CD stage that updates the next stage of production (ie dev or production)

Assets or resources we still need to begin this work:
- [ ] A CI management tool (ie Travis? GitHub Actions? Mirror on internal ORNL GitLab and use runners setup in CADES? I lean towards the latter since we need to deploy there as well for now)
- [ ] Runners - mainly if we go the ORNL GitLab / CADES route
- [ ] CI workflow script (ie `.gitlab-ci.yml` or a `.travis.yml` to code up this workflow)

**Comment by dvstans** [comment]
This work is in-progress via a different issue. Closing.
