### ISSUE TITLE
System - Improve versioning of system to allow backward compatibility

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#470]
Instead of using the protobuf version to lock all components to the same version, there should be a way to allow newer releases to permit older deployed components to work, if that is desired. Currently, a bump in the protobuf version causes all older components (Python CLI/API, Globus, Repos) to simply stop working. One simple solution is to simple have two version numbers - one for the protocol, and one for the system. A substantial difference in the protocol version would be blocked, but a system version difference would simply generate a warning to upgrade when possible.

**Comment by dvstans** [comment]
Also need to add version checks to repo server and python CLI/API. (web server already has check.)

**Comment by dvstans** [comment]
And the gridFTP auth worker.

**Comment by dvstans** [comment]
On second thought, it would be reasonable to say that the gridFTP authz API shall never change, so no need to do a version check.

**Comment by dvstans** [comment]
This has become more complex - the current system of using alphabetical order of messages had to be changed to file order to allow protobuf additions to not break backward compatibility. This required writing a python script to generate name/index mapping for python protobuf output files (and modifying cmake files as well). This now works, but the proto version needs to also be split into a major/minor component to work correctly (not done yet)

**Comment by dvstans** [comment]
Fixed. Added version check to repo server. Changed how proto files are loaded in all system services.

**Comment by JoshuaSBrown** [comment]
This actually, still breaks things.

**Comment by JoshuaSBrown** [comment]
This might very well be related to to https://github.com/ORNL/DataFed/issues/840
