### ISSUE TITLE
Web - Updating a record/collection causes annotaion icons to vanish

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#526]
This is being caused by the title update method for the data tree (and maybe search results) not accounting for annotations.

**Comment by dvstans** [comment]
This may be fixed. Verify.

**Comment by JoshuaSBrown** [comment]
I have not seen this being a problem can we remove this issue? I just updated a record that had a flag icon and the icon stayed.

**Comment by dvstans** [comment]
Closing as fixed.
