### ISSUE TITLE
Cannot do data get on ALCF Mira DTN

### ISSUE THREAD

**Issue by ssomnath** [ORNL/DataFed#534]
On ALCF's Theta LCF, I am able to put a file on the local filesystem into a data record on DataFed. However, I am simple unable to get data from a record already on DataFed onto the local filesystem.

```bash
somnaths@thetalogin6:~> module load datascience/mpi4py
somnaths@thetalogin6:~> which python
/soft/interpreters/python/3.6/intel/2019.3.075/bin/python
somnaths@thetalogin6:~> which pip
/soft/interpreters/python/3.6/intel/2019.3.075/bin/pip

somnaths@thetalogin6:~> pip install --user datafed
Collecting datafed
  Using cached https://files.pythonhosted.org/packages/fd/4e/7956ab7de2b07e9b5e1055986031848247f0f7566524ba64822994c58004/datafed-1.1.0.post0-py3-none-any.whl
Collecting protobuf>=3 (from datafed)
  Using cached https://files.pythonhosted.org/packages/30/79/510974552cebff2ba04038544799450defe75e96ea5f1675dbf72cc8744f/protobuf-3.13.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting wget>=3 (from datafed)
Collecting prompt-toolkit>=2 (from datafed)
  Using cached https://files.pythonhosted.org/packages/8a/aa/198e6a857e83ea8b711a6ae0c37717c0eb1b23ff52e3732a644fcd389cb3/prompt_toolkit-3.0.8-py3-none-any.whl
Collecting click>=7 (from datafed)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting pyzmq>=16 (from datafed)
  Using cached https://files.pythonhosted.org/packages/56/ff/34bf45e5cf8367edcf4946b26690f0982b3ec701b0a655edfe562d29e246/pyzmq-19.0.2-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.9 in /lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages (from protobuf>=3->datafed) (1.11.0)
Requirement already satisfied: setuptools in /lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages (from protobuf>=3->datafed) (39.0.1.post20190301)
Collecting wcwidth (from prompt-toolkit>=2->datafed)
  Using cached https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Installing collected packages: protobuf, wget, wcwidth, prompt-toolkit, click, pyzmq, datafed
Successfully installed click-7.1.2 datafed-1.1.0.post0 prompt-toolkit-3.0.8 protobuf-3.13.0 pyzmq-19.0.2 wcwidth-0.2.5 wget-3.2
You are using pip version 10.0.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

somnaths@thetalogin6:~> datafed setup
100% [................................................................] 40 / 40No local credentials loaded.
Manual authentication required.

User ID: somnaths
Password: 
OK

somnaths@thetalogin6:~> datafed
Welcome to DataFed CLI, version 1.1.0:0
Authenticated as u/somnaths
Use 'exit' command or Ctrl-C to exit shell.

root>ep default set alcf#dtn_mira
alcf#dtn_mira

root>data get d/10314975 .
Task ID:             task/29397079                                     
Type:                Data Get                                          
Status:              Ready                                             
Started:             10/27/2020,00:41                                  
Updated:             10/27/2020,00:41  
                                
root>exit

somnaths@thetalogin6:~> ls -hlt
total 1.0K
-rw-r--r-- 1 somnaths users 54 Oct 26 16:53 test_for_df.txt

somnaths@thetalogin6:~> ls -hlt
total 1.0K
-rw-r--r-- 1 somnaths users  0 Oct 27 00:41 10314975.h5
-rw-r--r-- 1 somnaths users 54 Oct 26 16:53 test_for_df.txt
```

See job details below:
 
DATA_TYPE
task
bytes_checksummed
0
bytes_transferred
0
command
API 0.10
completion_time
2020-10-27T00:43:34.000Z
deadline
2020-10-28T00:41:17.000Z
delete_destination_extra
false
destination_endpoint
alcf#dtn_mira
destination_endpoint_display_name
alcf#dtn_mira
destination_endpoint_id
e09e65f5-6d04-11e5-ba46-22000b92c6ec
directories
0
effective_bytes_per_second
0
encrypt_data
true
faults
1
files
1
files_skipped
0
files_transferred
0
history_deleted
false
is_delete
false
is_paused
false
is_transfer
true
owner_id
8f325dff-5d66-4e81-ae58-685a2fec92b6
preserve_timestamp
false
request_time
2020-10-27T00:41:17.000Z
source_endpoint
u_eiiq2lgi7fd7jfaggqdmnijiya#CADES-DataFed
source_endpoint_display_name
CADES-DataFed
source_endpoint_id
2b08184c-556e-11e9-a620-0a54e005f950
status
FAILED
task_id
1f415bde-17ed-11eb-893e-0a5521ff3f4b
type
TRANSFER
username
u_r4zf3725mzhidlsynbnc73eswy
verify_checksum
true
 
 
2020-10-26 08:43 pm
canceled
Canceled by the task owner
 
2020-10-26 08:43 pm
connection failed
 
Error (transfer)
Endpoint: CADES-DataFed (2b08184c-556e-11e9-a620-0a54e005f950)
Server: datafed.ornl.gov:2811
File: /data10t/cades-cnms/user/somnaths/10314975
Command: RETR /data10t/cades-cnms/user/somnaths/10314975
Message: Fatal FTP response

Details: 500-Command failed. : globus_gridftp_server_file.c:globus_l_gfs_file_server_write_cb:3075:\r\n500-callback failed.\r\n500-globus_xio_gsi.c:globus_l_xio_gsi_open_cb:1707:\r\n500-The GSI XIO driver failed to establish a connection via the underlying protocol.\r\n500-globus_xio_tcp_driver.c:globus_l_xio_tcp_system_connect_cb:2022:\r\n500-Unable to connect to 140.221.68.95:50244\r\n500-globus_xio_system_select.c:globus_l_xio_system_handle_write:1108:\r\n500-System error in connect: Connection timed out\r\n500-globus_xio: A system call failed: Connection timed out\r\n500 End.\r\n

**Comment by ssomnath** [comment]
Exact same bug applies to NERSC's file system as well. Configuration of CADES DataFed repository is suspected to be one possible source of the problem

**Comment by dvstans** [comment]
Fixed. Was an ORNL firewall issue.
