### ISSUE TITLE
Facility / Instrument / Administrator accounts

### ISSUE THREAD

**Issue by ssomnath** [ORNL/DataFed#546]
Along the lines of Globus Collaborator endpoints being used at NERSC for enabling their superficiality

**Comment by ssomnath** [comment]
Perhaps this is similar to a ``Project`` like object in DataFed. However, nobody is formally part of the facility permanently. This makes instruments behave like a user

**Comment by dvstans** [comment]
Not sure what you're describing. There is already a repository admin setting to allow facilities to manage local allocations. There is also an admin setting that (eventually) will allow additional (TBD) management functions.

**Comment by ssomnath** [comment]
Sorry for my vague comments. I wrote that really quickly while listening to a talk. NERSC has an interesting idea on treating an instrument (it's Globus endpoint) as a user to enable the many-to-one data sharing. I will try to find more information on this

**Comment by dvstans** [comment]
Unclear use case. Closing.
