### ISSUE TITLE
Use Enum instead of string / number values

### ISSUE THREAD

**Issue by ssomnath** [ORNL/DataFed#572]
For things like dependency types, consider using Enum instead of manually changing the mode to 0, 1, 2, etc.

**Comment by dvstans** [comment]
This ticket is too vague to be actionable. Please re-write as separate tickets for specific instances where enums should be used. Protobuf already defines enums when needed; however, dependency type is a special case and cannot be an enum as it needs to be expandable (a short string referencing an relationship definition).

**Comment by dvstans** [comment]
This isn't really actionable. Closing.
