### ISSUE TITLE
Automated creation of collections + permission when creating projects

### ISSUE THREAD

**Issue by ssomnath** [ORNL/DataFed#580]
When a project is created, Can we (optionally) automate the creation of collections to provide spaces for individual and collaborative work? For example, it would be nice for a user to know if they are part of a project, they will automatically have a collection whose alias and name match that of the username? Currently, the creation of a project requires the admin to manually create collections per user, and give them appropriate access via the web interface. There isn't a way for admins to automate how they want to set up projects. Can we also have the ``PROJECTSHARE`` collection to mimic typical project shared spaces?

**Comment by dvstans** [comment]
This is out of scope for DataFed. Project creation and structure will be under the control of individual facilities, and the DataFed Python API can be used by these facilities to integrate project creation with their internal user/project accounting systems.
