### ISSUE TITLE
CommandLib - dataGet ID parameter should accept single values and arrays

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#581]
Currently this method only accepts arrays. Need to add check for single/multiple values and handle both.

**Comment by ssomnath** [comment]
[this commit](https://github.com/ORNL/DataFed/commit/3baa33cca15323da1fd26346edb808550505f1ba) should solve the problem. Has not yet been tested though

**Comment by dvstans** [comment]
Fixed
