### ISSUE TITLE
Web - Change active info tab current is disabled

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#630]
When a new item is selected and the current tab is disabled (due to being selected from a previous item), then reset the tab to the general tab which is always enabled.

**Comment by dvstans** [comment]
Need to discuss. Some users may want the tab selection to remain stable - for example, when browsing through records inspecting metadata.

**Comment by JoshuaSBrown** [comment]
# Clarification
When a record is selected the right pane of the DataFed web UI contains three tabs General, Metadata and Notes. When a record is selected it by default opens to the General tab.

# Opinion

I'm not sure I agree that this behavior needs to be changed. I think it is more intuitive that the tab that was selected remains open. So if a user opens a record and then selects the metadata tab that tab should now remain the default even if a new record is selected, this should remain true even if the current record does not have any metadata. I see it being a fairly common case that users go through a bunch of records looking for similar information if DataFed is switching the open tab it would be a bit annoying to switch it back each time.

**Comment by dvstans** [comment]
I agree - closing.
