### ISSUE TITLE
System - Add data record download target options

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#634]
Currently will download to filename <ID>.<EXT> or to original source filename is selected. Need to provide more control over download names with optional name components: prefix, suffix, ID, original name, extensions, metadata fields.  This will allow users to better understand the downloaded files from a filesystem / process view.

**Comment by JoshuaSBrown** [comment]
This is similar: https://github.com/ORNL/DataFed/issues/710

**Comment by dvstans** [comment]
Agreed. Closing this one.
