### ISSUE TITLE
Pick project dialog includes inaccessible/irrelevant projects

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#746]
In the future, the list of projects will be very large (!10,000+), so finding a specific project in a pick dialog will be very hard. In addition, the vast majority of these projects are either inaccessible (for personal projects), or irrelevant (no published data in catalog). The picker dialog should filter the projects appropriately - either by access, or by published data.

**Comment by JoshuaSBrown** [comment]
If we don't support public data will this be as large a problem?

**Comment by dvstans** [comment]
This issue is currently irrelevant because we got rid of personal projects. Only repo admins can create projects. And yes, without catalogs it even less relevant. Closing.
