### ISSUE TITLE
libprotobuf-dev not listed a required dependency

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#864]
This package is required to build datafed but not mentioned in build docs.

**Comment by JoshuaSBrown** [comment]
The package is now output as part of the cmake build process and the path to the library is explicitly listed. This has in the past been a major source of headaches. To further address the issue static libraries are used and built into datafed to make the it more interoperatble. DataFed even now has some dependency install scripts that will install the dependencies for you with pinned version.
